<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<CodeBlocks_layout_file>
	<FileVersion major="1" minor="0" />
	<ActiveTarget name="Debug" />
	<File name="extend_exception.hpp" open="1" top="0" tabpos="2" split="0" active="1" splitpos="0" zoom_1="8" zoom_2="0">
		<Cursor>
			<Cursor1 position="76" topLine="8" />
		</Cursor>
	</File>
	<File name="extend_exception.cpp" open="1" top="1" tabpos="3" split="0" active="1" splitpos="0" zoom_1="9" zoom_2="0">
		<Cursor>
			<Cursor1 position="502" topLine="0" />
		</Cursor>
	</File>
	<File name="test.cpp" open="1" top="0" tabpos="1" split="0" active="1" splitpos="0" zoom_1="7" zoom_2="0">
		<Cursor>
			<Cursor1 position="1001" topLine="22" />
		</Cursor>
		<Folding>
			<Collapse line="18" />
		</Folding>
	</File>
	<File name="math.cpp" open="0" top="0" tabpos="1" split="0" active="1" splitpos="0" zoom_1="8" zoom_2="0">
		<Cursor>
			<Cursor1 position="268" topLine="7" />
		</Cursor>
	</File>
	<File name="math.hpp" open="1" top="0" tabpos="4" split="0" active="1" splitpos="0" zoom_1="6" zoom_2="0">
		<Cursor>
			<Cursor1 position="77" topLine="0" />
		</Cursor>
	</File>
</CodeBlocks_layout_file>
